/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Navigation: typeof import('./src/components/navigation/Navigation.vue')['default']
    NavigationBar: typeof import('./src/components/navigation/NavigationBar.vue')['default']
    NavigationItem: typeof import('./src/components/navigation/NavigationItem.vue')['default']
    NavigationSection: typeof import('./src/components/navigation/NavigationSection.vue')['default']
    NavigationTopBar: typeof import('./src/components/navigation/NavigationTopBar.vue')['default']
    OrderCartTotals: typeof import('./src/components/sales/OrderCartTotals.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
